### ISSUE TITLE
Infinite retry loop

### ISSUE THREAD

**Issue by jamesholcomb** [mfelicio/NDomain#3]
I'm running into a scenario where a message is caught in an endless retry loop using the `RedisTransport`.  The exception happens here:

```
if (handler == null)
{
    // TODO: send message to an error queue?
    throw new Exception(
        string.Format("Handler {0} not found or doesn't process message {1}", handlerName, message.Name));
}
```

I think this happened as a result of me converting an existing event handler to a command handler.  My test app is configured to use `LocalSubscriptionStore`.

Curious how you were coming along with the error queue feature.

**Comment by mfelicio** [comment]
Oh I can see that happening. Even if you change the handler type, the message that is in the queue still has an header that contains the name of the handler that will process it. This is to ensure that each handler has its own copy of the message, so you can have multiple handlers for the same message without side effects.

I do have a retry counter per message, but I haven't introduced the concept of an error or poison queue. It will exist for sure. Thank you for opening the issue.

**Comment by mfelicio** [comment]
I've been away for some time and just picked this up this week. I have now added support for max retries and dead letter queues, configurable per processor. Dead lettering is enabled by default, so if a message fails for the configured max retries (defaults to 10) it will be moved to a dead letter queue and removed from original queue. If dead lettering is disabled it will simply be removed from the original queue.
